Added functions to run Express and Rails service wizards
buildlyio/buildly-cli pull request #12
Opened 2019-11-27 17:07 UTC by msradam

Added functions similar to the CreateDjangoService call that will run the docker-compose files from the Express and Rails service wizard subrepositories.

2019-11-29 13:07 UTC, jefmoura requested changes

2019-11-29 13:07 UTC, jefmoura commented on init.sh
> +createExpressService()
This is function isn't used anywhere. How/Where is it going to be called?

2019-11-29 13:07 UTC, jefmoura commented on init.sh
> +createRailsService()
This is function isn't used anywhere. How/Where is it going to be called?

2019-11-29 13:07 UTC, jefmoura commented on init.sh
> +  if [ ! -d express-service-wizard ]; then
This folder doesn't exist, so the script always prints an error and exit

2019-11-29 13:07 UTC, jefmoura commented on init.sh
> +  if [ ! -d rails-service-wizard ]; then
This folder doesn't exist, so the script always prints an error and exit

2019-11-29 13:07 UTC, jefmoura commented on init.sh
> +  docker-compose run --rm express_service_wizard || echo "Docker not configured, installed or running"
There's no `express_service_wizard`, so it always prints `Docker not configured, installed or running`

2019-11-29 13:07 UTC, jefmoura commented on init.sh
> +  docker-compose run web rails new YourRailsApplication --force --no-deps --database=postgresql || echo "Docker not configured, installed or running"
There's no `YourRailsApplication`, so it always prints `Docker not configured, installed or running`

2019-11-29 13:07 UTC, jefmoura commented on init.sh
> -    --set buildly.image.pullPolicy=IfNotPresent
This code block doesn't need to be removed.

2019-11-29 13:07 UTC, jefmoura commented on init.sh
> +  setupServices
This code block doesn't need to be changed to add new servicer wizards

2019-11-29 13:07 UTC, jefmoura commented on init.sh
> -
We need a good message when the help option is used

2019-11-29 13:07 UTC, jefmoura commented on init.sh
> +  print_message "error" "$MSG"
We need to print a helpful message and stop the script when no option is used as some Unix commands already do.

2019-12-10 15:09 UTC, glind approved these changes

2020-01-06 16:32 UTC, jefmoura commented
Currently, we don't have new and ready to be used application wizards, so we'll close this pull request and this functionality will be implemented in the near future when we have new wizards available.

2020-01-06 16:32 UTC, closed without merging